import Foundation
import MClashNetworkShared
import Testing
@testable import MClashApp

/// Opt-in acceptance test for a copied Application Support tree. The source
/// path must already be an isolated copy; this test never opens the GUI,
/// changes the system proxy, or loads a Network Extension manager.
struct LocalProfileShadowSmokeTests {
    @MainActor
    @Test("Copied local profiles compile and run in an isolated mihomo")
    func copiedProfilesCompileAndRun() async throws {
        let environment = ProcessInfo.processInfo.environment
        guard let shadowPath = environment["MCLASH_SHADOW_ROOT"],
              let corePath = environment["MCLASH_TEST_CORE"],
              let geoDataPath = environment["MCLASH_SHADOW_GEODATA"],
              let originURL = environment["MCLASH_SHADOW_ORIGIN_URL"] else {
            return
        }

        let layout = ProfileDirectoryLayout(rootDirectory: URL(filePath: shadowPath))
        let profileStore = try ProfileStore(layout: layout)
        let profiles = try await profileStore.profiles()
        guard !profiles.isEmpty else { throw ShadowSmokeFailure.noProfiles }
        var profileSnapshots: [ProfileID: Data] = [:]
        for profile in profiles {
            profileSnapshots[profile.id] = try await profileStore
                .configurationData(for: profile.id)
        }
        let storedDocument = try await ConfigurationStore(layout: layout).load()
        guard storedDocument != .empty else { throw ShadowSmokeFailure.noConfiguration }

        let defaultsName = "MClash.LocalProfileShadow.\(UUID().uuidString)"
        guard let defaults = UserDefaults(suiteName: defaultsName) else {
            throw ShadowSmokeFailure.preferencesUnavailable
        }
        defaults.set(false, forKey: AppModel.autoConnectOnLaunchKey)
        defaults.set(false, forKey: AppModel.connectionDesiredOnLaunchKey)
        defaults.set(false, forKey: AppModel.autoEnableSystemProxyKey)
        defer { defaults.removePersistentDomain(forName: defaultsName) }

        let model = makeTestAppModel(
            systemProxyManager: SystemProxyManager(backend: ShadowSystemProxyBackend()),
            profileDirectoryLayout: layout,
            profileStoreOverride: profileStore,
            preferenceDefaults: defaults
        )
        try await model.saveConfigurationDocument(storedDocument)
        await model.synchronizeConfigurationSources()
        let preset = try await model.installCommonProxyGroupPreset()

        var runtimeDocument = preset.document
        guard let workspaceIndex = runtimeDocument.workspaces.firstIndex(where: {
            $0.id == runtimeDocument.currentWorkspace?.id
        }) else { throw ShadowSmokeFailure.noConfiguration }
        runtimeDocument.workspaces[workspaceIndex].nodeIDs = []

        let ports = try LocalPortProbe().availableTCPAndUDPPorts(count: 3)
        let httpPort = ports[0]
        let socksPort = ports[1]
        let controllerPort = ports[2]
        let workspaceEntranceIDs = Set(
            runtimeDocument.workspaces[workspaceIndex].entranceIDs
        )
        for index in runtimeDocument.entrances.indices
        where workspaceEntranceIDs.contains(runtimeDocument.entrances[index].id) {
            switch runtimeDocument.entrances[index].kind {
            case .http:
                runtimeDocument.entrances[index].enabled = true
                runtimeDocument.entrances[index].bindAddress = "127.0.0.1"
                runtimeDocument.entrances[index].port = httpPort
            case .socks5:
                runtimeDocument.entrances[index].enabled = true
                runtimeDocument.entrances[index].bindAddress = "127.0.0.1"
                runtimeDocument.entrances[index].port = socksPort
            case .appRouting, .tun:
                runtimeDocument.entrances[index].enabled = false
            }
        }
        if let dnsIndex = runtimeDocument.dnsPolicies.firstIndex(where: {
            $0.id == runtimeDocument.workspaces[workspaceIndex].dnsPolicyID
        }) {
            runtimeDocument.dnsPolicies[dnsIndex].takeoverEnabled = false
        }

        for workspace in runtimeDocument.workspaces {
            _ = try ConfigurationCompiler().compile(
                document: runtimeDocument,
                workspaceID: workspace.id
            )
        }
        let compiled = try ConfigurationCompiler().compile(document: runtimeDocument)
        let yaml = String(decoding: compiled.yaml, as: UTF8.self)
        guard yaml.contains("# Generated by MClash"),
              yaml.contains(ConfigurationProxyGroupPreset.mainGroupName),
              !yaml.contains("external-controller:"),
              !yaml.contains("📹 油管视频"),
              !yaml.contains("rule-providers:") else {
            throw ShadowSmokeFailure.sourceStrategyLeaked
        }
        let runtimeURL = layout.runtimeDirectory.appending(
            path: "shadow-config.yaml",
            directoryHint: .notDirectory
        )
        try compiled.yaml.write(to: runtimeURL, options: .atomic)

        for profile in profiles {
            guard try await profileStore.configurationData(for: profile.id)
                    == profileSnapshots[profile.id] else {
                throw ShadowSmokeFailure.profileChanged
            }
        }

        let coreHome = layout.rootDirectory.appending(
            path: "ShadowCoreHome",
            directoryHint: .isDirectory
        )
        try BundledGeoDataInstaller(
            sourceDirectory: URL(filePath: geoDataPath)
        ).installIfNeeded(into: coreHome)
        let supervisor = CoreSupervisor()
        let secret = "shadow-\(UUID().uuidString)"
        let launch = CoreLaunchConfiguration(
            binaryURL: URL(filePath: corePath),
            homeDirectory: coreHome,
            configURL: runtimeURL,
            controllerPort: UInt16(controllerPort),
            secret: secret
        )

        do {
            try await supervisor.start(launch)
            guard case let .running(session) = await supervisor.state() else {
                throw ShadowSmokeFailure.coreDidNotStart
            }
            let client = try MihomoAPIClient(
                baseURL: session.endpoint,
                secret: session.secret,
                requestTimeout: 10
            )
            let version = try await client.fetchVersion()
            let proxies = try await client.fetchProxies()
            guard version.version.hasPrefix("alpha-"),
                  let main = proxies.proxies[ConfigurationProxyGroupPreset.mainGroupName],
                  main.all.contains(ConfigurationProxyGroupPreset.unitedStatesGroupName),
                  main.all.contains(ConfigurationProxyGroupPreset.japanGroupName),
                  main.all.contains(ConfigurationProxyGroupPreset.directGroupName) else {
                throw ShadowSmokeFailure.groupHierarchyMissing
            }

            try await client.selectProxy(
                group: ConfigurationProxyGroupPreset.mainGroupName,
                proxy: ConfigurationProxyGroupPreset.directGroupName
            )
            let localStatus = try curlStatus(
                proxyPort: httpPort,
                url: originURL,
                timeout: 10
            )
            guard (200..<400).contains(localStatus) else {
                throw ShadowSmokeFailure.localProxyRequestFailed(localStatus)
            }

            var successfulExternalGroups: [String] = []
            for (groupName, hintKey) in [
                (ConfigurationProxyGroupPreset.unitedStatesGroupName, "MCLASH_SHADOW_US_NODE_HINT"),
                (ConfigurationProxyGroupPreset.japanGroupName, "MCLASH_SHADOW_JP_NODE_HINT"),
            ] {
                guard let group = proxies.proxies[groupName] else { continue }
                if let hint = environment[hintKey],
                   let candidate = group.all.first(where: {
                       $0.localizedCaseInsensitiveContains(hint)
                   }) {
                    try? await client.selectProxy(group: groupName, proxy: candidate)
                }
                do {
                    try await client.selectProxy(
                        group: ConfigurationProxyGroupPreset.mainGroupName,
                        proxy: groupName
                    )
                    let status = try curlStatus(
                        proxyPort: httpPort,
                        url: "https://www.gstatic.com/generate_204",
                        timeout: 20
                    )
                    if (200..<400).contains(status) {
                        successfulExternalGroups.append(groupName)
                    }
                } catch {
                    // Try both independent regional paths and report the
                    // aggregate below; one provider route may be offline.
                }
            }
            guard !successfulExternalGroups.isEmpty else {
                throw ShadowSmokeFailure.noExternalRegionalRoute
            }

            await supervisor.stop()
            guard case .stopped = await supervisor.state() else {
                throw ShadowSmokeFailure.coreDidNotStop
            }
            print(
                "Local profile shadow passed: profiles=\(profiles.count) "
                    + "nodes=\(runtimeDocument.nodes.count) "
                    + "groups=\(runtimeDocument.workspaces[workspaceIndex].proxyGroupIDs.count) "
                    + "rules=\(runtimeDocument.workspaces[workspaceIndex].ruleIDs.count) "
                    + "yamlBytes=\(compiled.yaml.count) "
                    + "externalGroups=\(successfulExternalGroups.joined(separator: ","))"
            )
        } catch {
            await supervisor.stop()
            throw error
        }
    }

    private func curlStatus(
        proxyPort: Int,
        url: String,
        timeout: Int
    ) throws -> Int {
        let process = Process()
        process.executableURL = URL(filePath: "/usr/bin/curl")
        process.arguments = [
            "--silent", "--show-error", "--output", "/dev/null",
            "--write-out", "%{http_code}", "--noproxy", "",
            "--proxy", "http://127.0.0.1:\(proxyPort)",
            "--max-time", String(timeout), url,
        ]
        let output = Pipe()
        process.standardOutput = output
        process.standardError = Pipe()
        try process.run()
        process.waitUntilExit()
        let value = String(
            decoding: output.fileHandleForReading.readDataToEndOfFile(),
            as: UTF8.self
        )
        guard process.terminationStatus == 0,
              let status = Int(value.trimmingCharacters(in: .whitespacesAndNewlines)) else {
            throw ShadowSmokeFailure.curlFailed(Int(process.terminationStatus))
        }
        return status
    }
}

private struct ShadowSystemProxyBackend: SystemProxyBackend {
    func enabledNetworkServices() throws -> [SystemProxyNetworkService] { [] }
    func proxyStates(
        for services: [SystemProxyNetworkService]
    ) throws -> [SystemProxyServiceState] { [] }
    func applyProxyStates(_ states: [SystemProxyServiceState]) throws {
        throw ShadowSmokeFailure.systemProxyMutationAttempted
    }
}

private enum ShadowSmokeFailure: Error {
    case noProfiles
    case noConfiguration
    case preferencesUnavailable
    case sourceStrategyLeaked
    case profileChanged
    case coreDidNotStart
    case coreDidNotStop
    case groupHierarchyMissing
    case localProxyRequestFailed(Int)
    case noExternalRegionalRoute
    case curlFailed(Int)
    case systemProxyMutationAttempted
}
